### ISSUE TITLE
Corrupts dumps on 3.68 and H-Encore

### ISSUE THREAD

**Issue by Andiweli** [dnasdw/Vitamin#1]
Hi there!
Great work, I don't know if it's still under development or is abandoned...
I just wanted to mention, that with the latest Henkaku for 3.68 (H-Encore) the Vitamin 2.0 app seems not to work as expected. Dumping games results in a corrupted game - the dump too doesn't even start.
Best regards, keep it up!

**Comment by DanIsDaMan** [comment]
I have also experienced this issue with viramin on 3.68 h-encore.

**Comment by Danny4096** [comment]
I have also experienced this issue with Vitamin on 3.68 h-encore.
